version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:region:account-id:task-definition/ddtesttaskdef"
        LoadBalancerInfo:
          ContainerName: "flaskapptest"
          ContainerPort: 5000
